version: 0.0.1
---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    master:
      url: jdbc:mysql://172.24.76.215:3306/shelter-zoo?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
      username: admin
      password: admin
      driver-class-name: com.mysql.cj.jdbc.Driver
    slave:
      url: jdbc:mysql://127.0.0.1:3306/shelter-zoo?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
      username: admin
      password: admin
      driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 127.0.0.1
    port: 6379
  session:
    store-type: redis
#server:
#  port: 8080
pagehelper:
  helper-dialect: h2
  auto-dialect: true
  page-size-zero: false
  reasonable: true
  offset-as-page-num: false
  row-bounds-with-count: false
  auto-runtime-dialect: false
  close-conn: true
  default-count: true
# 개발 중 필요시 Mybatis SQL 요청 쿼리 확인용도
logging:
  level:
    com:
      noint:
        shelterzoo:
          domain: trace

---
server:
  shutdown: graceful
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    master:
      url: jdbc:mysql://${MYSQL_URL}:${MYSQL_PORT}/${MYSQL_PROJECT_DB}?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
      username: ${MYSQL_USER}
      password: ${MYSQL_PASSWORD}
      driver-class-name: com.mysql.cj.jdbc.Driver
    slave:
      url: jdbc:mysql://${MYSQL_SLAVE_URL}:${MYSQL_PORT}/${MYSQL_PROJECT_DB}?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
      username: ${MYSQL_USER}
      password: ${MYSQL_PASSWORD}
      driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: ${REDIS_URL}
    port: ${REDIS_PORT}
  session:
    store-type: redis
  tomcat:
    threads:
      max: 50 # 생성할 수 있는 thread의 총 개수
      min-spare: 10 # 항상 활성화 되어있는(idle) thread의 개수
    accept-count: 50 # 작업큐의 사이즈
    connection-timeout: 30000
pagehelper:
  helper-dialect: h2
  auto-dialect: true
  page-size-zero: false
  reasonable: true
  offset-as-page-num: false
  row-bounds-with-count: false
  auto-runtime-dialect: false
  close-conn: true
  default-count: true

